Repository TejasJD/HorizonEngine2D, pull requests merged in 2022-12, with the labels that each got.

#132 Content browser fix
  HorizonEditor/src/ContentBrowser/ContentBrowser.cpp
Labels: bug

#135 View menu item, Panels enabling and disabling.
  HorizonEditor/src/ContentBrowser/ContentBrowser.cpp
  HorizonEditor/src/EditorLayer.cpp
Labels: enhancement

#137 Optimize the content browser
  HorizonEditor/include/ContentBrowser.h
  HorizonEditor/src/ContentBrowser/ContentBrowser.cpp
Labels: enhancement

#140 Added More Methods to Script Library.
  HorizonEditor/ScriptCoreLib/ScriptCoreLib.csproj
  HorizonEditor/ScriptCoreLib/Source/Core/InternalCalls.cs
  HorizonEditor/ScriptCoreLib/Source/ECS/Components.cs
  HorizonEditor/ScriptCoreLib/Source/Math/Vector4.cs
  HorizonEditor/Scripts/ScriptCoreLib.dll
  HorizonEngine/src/HorizonEngine/Scripting/ScriptRegistry.cpp
Labels: enhancement

#124 Adding documentation to the code base
  HorizonEditor/include/EditorLayer.h
  HorizonEditor/src/EditorLayer.cpp
  HorizonEditor/src/Main.cpp
  HorizonEngine/Platform/OpenGL/FDWindows.cpp
  HorizonEngine/Platform/OpenGL/GLContext.cpp
  HorizonEngine/Platform/OpenGL/GLContext.h
  HorizonEngine/Platform/OpenGL/GLShader.cpp
  HorizonEngine/Platform/OpenGL/GLShader.h
  HorizonEngine/Platform/OpenGL/GLWindow.h
  HorizonEngine/src/HorizonEngine/App.cpp
  HorizonEngine/src/HorizonEngine/App.h
  HorizonEngine/src/HorizonEngine/AssetManagement/AssetManager.cpp
  HorizonEngine/src/HorizonEngine/AssetManagement/AssetManager.h
  HorizonEngine/src/HorizonEngine/Audio/AudioSource.h
  HorizonEngine/src/HorizonEngine/Audio/SoundDevice.h
  HorizonEngine/src/HorizonEngine/Camera/CameraController.h
  HorizonEngine/src/HorizonEngine/Codes/KeyboardCodes.h
  HorizonEngine/src/HorizonEngine/Codes/MouseCodes.h
  HorizonEngine/src/HorizonEngine/Core/TimeStep.h
  HorizonEngine/src/HorizonEngine/Events/ApplicationEvent.h
  HorizonEngine/src/HorizonEngine/Events/Event.h
  HorizonEngine/src/HorizonEngine/Events/MouseEvent.h
  HorizonEngine/src/HorizonEngine/FileManagement/Project.cpp
  HorizonEngine/src/HorizonEngine/FileManagement/Project.h
  HorizonEngine/src/HorizonEngine/FileManagement/ProjectFile.h
  HorizonEngine/src/HorizonEngine/FileManagement/ProjectManager.cpp
  HorizonEngine/src/HorizonEngine/FileManagement/ProjectManager.h
  HorizonEngine/src/HorizonEngine/ImGui/ImguiLayer.cpp
  HorizonEngine/src/HorizonEngine/Input.h
  HorizonEngine/src/HorizonEngine/Layer.h
  HorizonEngine/src/HorizonEngine/LayerStack.cpp
  HorizonEngine/src/HorizonEngine/LayerStack.h
  HorizonEngine/src/HorizonEngine/Logging/Logging.cpp
  HorizonEngine/src/HorizonEngine/Logging/Logging.h
  HorizonEngine/src/HorizonEngine/Renderer/Buffer.cpp
  HorizonEngine/src/HorizonEngine/Renderer/FrameBuffer.cpp
  HorizonEngine/src/HorizonEngine/Renderer/FrameBuffer.h
  HorizonEngine/src/HorizonEngine/Renderer/RenderCall.cpp
  HorizonEngine/src/HorizonEngine/Renderer/RenderCall.h
  HorizonEngine/src/HorizonEngine/Renderer/RenderContext.cpp
  HorizonEngine/src/HorizonEngine/Renderer/RenderContext.h
  HorizonEngine/src/HorizonEngine/Renderer/Renderer.cpp
  HorizonEngine/src/HorizonEngine/Renderer/Renderer.h
  HorizonEngine/src/HorizonEngine/Renderer/Renderer2D.cpp
  HorizonEngine/src/HorizonEngine/Renderer/RendererAPI.cpp
  HorizonEngine/src/HorizonEngine/Renderer/RendererAPI.h
  HorizonEngine/src/HorizonEngine/Renderer/Shader.cpp
  HorizonEngine/src/HorizonEngine/Renderer/Shader.h
  HorizonEngine/src/HorizonEngine/Renderer/Sprite.cpp
  HorizonEngine/src/HorizonEngine/Renderer/Texture.cpp
  HorizonEngine/src/HorizonEngine/Renderer/VertexArray.cpp
  HorizonEngine/src/HorizonEngine/Scripting/ScriptRegistry.h
  HorizonEngine/src/HorizonEngine/Utils/Math.cpp
  HorizonEngine/src/HorizonEngine/Utils/Math.h
  HorizonEngine/src/HorizonEngine/Utils/Time.cpp
  HorizonEngine/src/HorizonEngine/Utils/Time.h
  HorizonEngine/src/HorizonEngine/Utils/TreeNode.h
  HorizonEngine/src/HorizonEngine/Window.cpp
  HorizonEngine/src/HorizonEngine/Window.h
Labels: documentation
